config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    # :omniauth_callbacks => "users/omniauth_callbacks",
    # sessions: 'users/sessions',
    # registrations: 'users/registrations',
    # confirmations: 'users/confirmations'
  }

  root 'pages#index'

  namespace :admin do
    resources :letters, :subjects
  end

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  resources :letters
  resources :subjects
  resources :student_registrations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lecture.rb
class Lecture < User
end

app/models/lecture_profile.rb
class LectureProfile < User
end

app/models/letter.rb
class Letter < ApplicationRecord
  before_create :tanggal_surat, :nomor_surat, :set_tahun_ajaran
  attr_accessor :tmp_photo
  def tanggal_surat
    self.letter_date = Time.created_at.strftime("%d-%m-%Y")
  end

  def nomor_surat
    if Time.now == Time.beginning_of_month
      self.letter_number = i
      i = 0
      i = i + 1
    end
  end

  def set_tahun_ajaran
    self.education_year = Time.now.strftime('%Y')/Time.now.strftime('%Y').to_i + 1
  end
  
  def self.letter_list
    ["Surat Keterangan Kuliah Biasa","Surat Keterangan Kuliah Tanggungan", "Surat Keterangan Lulus", "Surat Keterangan Akreditasi Biasa", "Surat Keterangan Akreditasi Alumni", "Surat Rekomendasi Kegiatan", "Surat Rekomendasi Beasiswa", "Surat Berkelakuan Baik" , "Cuti Akademik", "Surat Keterangan Pindah Kampus"]
  end

  def self.deparment_list
    ["Teknik Pertambangan", "Teknik Mesin", "Teknik Informatika"]
  end

  def self.ganjil_genap
    ["Semester Ganjil", "Semester Genap"]
  end

  def self.administration_list
    ["Drs. Iskandar, BE"]
  end

end

app/models/staff.rb
class Staff < User
end

app/models/staff_profile.rb
class StaffProfile < User
end

app/models/student.rb
class Student < User
end

app/models/student_profile.rb
class StudentProfile < User
end

app/models/student_registration.rb
class StudentRegistration < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: [:show, :edit, :update, :destroy]

  def new
    @letter = Letter.new
  end

  def create
    @letter = Letter.create(letter_params)
    if @letter.save
      respond_to do |format|
        format.html {redirect_to root_url, notice: "Surat Berhasil Dibuat"}
        format.json { render json: @letter }
      end
    end
  end

  def show

  end
  
  private
  def set_letter
    @letter = Letter.find(params[:id])
  end
  def letter_params
    params.require(:letter).permit(:name, :stambuk, :department, :birth_place, :birth_date, :address, :phone, :yudisium_date, :essay_title, :parents_name, :employee_number, :employee_level, :parents_phone, :company_name, :letter_kind, :letter_date, :letter_number, :semester_genap_ganjil, :education_year, :formers, :disposition_date, :administration_head, :number_diploma_university, :number_diploma_faculty)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/student_registrations_controller.rb
class StudentRegistrationsController < ApplicationController
  def new
  end

  def create
  end

  def show
  end
end

app/helpers/admin/letters_helper.rb
module Admin::LettersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/student_registrations_helper.rb
module StudentRegistrationsHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ADMIN | UPRI</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'upri.ico' %>
    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/partial/admin_navigation" %>
    <div class="notice">
      <%= notice %>
    </div>
    <div class="alert">
      <%= alert %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FAKULTAS TEKNIK | UPRI</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'upri.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/partial/navigation" %>
    <div class="notice">
      <%= notice %>
    </div>
    <div class="alert">
      <%= alert %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FAKULTAS TEKNIK | UPRI</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'upri.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/partial/navigation" %>
    <div class="notice">
      <%= notice %>
    </div>
    <div class="alert">
      <%= alert %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/partial/_admin_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#"><%= image_tag("upri.ico", width:"", height:"50", alt:"") %></a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li><%= link_to "Beranda", root_url, class: "nav-link" %></li>
      <li><%= link_to "Dosen", "#", class: "nav-link" %></li>
      <li><%= link_to "Mahasiswa", "#", class: "nav-link" %></li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Persuratan
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
         <%= link_to "Buat", new_letter_path, class: "dropdown-item" %>
         <%= link_to "Info", "#", class: "dropdown-item" %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Kuliah
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
         <a class="dropdown-item" href="#">KRS</a>
         <a class="dropdown-item" href="#">Jadwal</a>
         <a class="dropdown-item" href="#">Mata Kuliah</a>
         <a class="dropdown-item" href="#">Nilai</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          KKN
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Info</a>
          <a class="dropdown-item" href="#">Kelompok</a>
        </div>
      </li>
            <%#= link_to "Mahasiswa", destroy_user_session_path, method: :delete,  class: "nav-link" %>
    </ul>
    <ul class="navbar-nav mt-2 mt-md-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         MABA
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
         <a class="dropdown-item" href="#">Lihat</a>
         <a class="dropdown-item" href="#">Registrasi</a>
        </div>
      </li>
      <li class="pull-right"><%= link_to "Login", "#", class: "nav-link" %></li>
      <li class="pull-right"><%= link_to "Daftar", "#", class: "nav-link" %></li>
    </ul>


  </div>
</nav>

app/views/layouts/partial/_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#"><%= image_tag("upri.ico", width:"", height:"50", alt:"") %></a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li><%= link_to "Beranda", root_url, class: "nav-link" %></li>
      <li><%= link_to "Dosen", "#", class: "nav-link" %></li>
      <li><%= link_to "Mahasiswa", "#", class: "nav-link" %></li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Persuratan
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
         <%= link_to "Buat", new_letter_path, class: "dropdown-item" %>
         <%= link_to "Info", "#", class: "dropdown-item" %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Kuliah
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
         <a class="dropdown-item" href="#">KRS</a>
         <a class="dropdown-item" href="#">Jadwal</a>
         <a class="dropdown-item" href="#">Mata Kuliah</a>
         <a class="dropdown-item" href="#">Nilai</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          KKN
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Info</a>
          <a class="dropdown-item" href="#">Kelompok</a>
        </div>
      </li>
            <%#= link_to "Mahasiswa", destroy_user_session_path, method: :delete,  class: "nav-link" %>
    </ul>
    <ul class="navbar-nav mt-2 mt-md-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         MABA
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
         <a class="dropdown-item" href="#">Lihat</a>
         <a class="dropdown-item" href="#">Registrasi</a>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class="pull-right"><%= link_to "Logout", destroy_user_session_path, class: "nav-link" %></li>
      <% else %>
        <li class="pull-right"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <li class="pull-right"><%= link_to "Daftar", new_user_registration_path, class: "nav-link" %></li>
      <% end %>
    </ul>


  </div>
</nav>

app/views/pages/index.html.erb
<section class="page_index" align="center">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <h4 class="hidden-sm-down">YAYASAN PERGURUAN TINGGI KARYA DHARMA MAKASSAR</h4>
    <h4 class="hidden-md-up">YPTKD MAKASSAR</h4>
    <h2 class="hidden-sm-down">UNIVERSITAS PEJUANG REPUBLIK INDONESIA</h2>
    <h3 class="hidden-md-up">UPRI</h2>
    <h3 class="hidden-sm-down">FAKULTAS TEKNIK</h2>
    <h5 >SISTEM INFORMASI DAN AKADEMIK MAHASISWA</h3>
  </div>

  <%= image_tag("upri.png")  %>
    
  <div class="col-xs-12 col-sm-12 col-md-12">
    <h5 class="visible-sm visible-md visible-lg">TAHUN AJARAN</h5>
    <p class="visible-sm visible-md visible-lg"><%= Time.now.strftime('%Y')%>/<%= Time.now.strftime('%Y').to_i + 1 %></p>
  </div>
</section>